# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3d5024d15c9bd2198d677600bfa68cbfe7cea34f453f421194030c163a6cd7df9eba14d4a1a05e91fb415988833c41d56473dd872968f0c228305112ce6d822

test:
  secret_key_base: cdfec03d5b0731c9dfa1e2564da3659de7bd9a83decc336c1444690b0f766e3c510c1025bbe67f095119cedaf9143116c607e90d0c52061d7169df095543cf1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
